// Generated by gencpp from file robot_vision_lectures/XYZarray.msg
// DO NOT EDIT!


#ifndef ROBOT_VISION_LECTURES_MESSAGE_XYZARRAY_H
#define ROBOT_VISION_LECTURES_MESSAGE_XYZARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace robot_vision_lectures
{
template <class ContainerAllocator>
struct XYZarray_
{
  typedef XYZarray_<ContainerAllocator> Type;

  XYZarray_()
    : points()  {
    }
  XYZarray_(const ContainerAllocator& _alloc)
    : points(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::robot_vision_lectures::XYZarray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_vision_lectures::XYZarray_<ContainerAllocator> const> ConstPtr;

}; // struct XYZarray_

typedef ::robot_vision_lectures::XYZarray_<std::allocator<void> > XYZarray;

typedef boost::shared_ptr< ::robot_vision_lectures::XYZarray > XYZarrayPtr;
typedef boost::shared_ptr< ::robot_vision_lectures::XYZarray const> XYZarrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_vision_lectures::XYZarray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_vision_lectures::XYZarray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_vision_lectures::XYZarray_<ContainerAllocator1> & lhs, const ::robot_vision_lectures::XYZarray_<ContainerAllocator2> & rhs)
{
  return lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_vision_lectures::XYZarray_<ContainerAllocator1> & lhs, const ::robot_vision_lectures::XYZarray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_vision_lectures

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_vision_lectures::XYZarray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_vision_lectures::XYZarray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_vision_lectures::XYZarray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_vision_lectures::XYZarray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_vision_lectures::XYZarray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_vision_lectures::XYZarray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_vision_lectures::XYZarray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3fb3f9dacc279b964c4c8341122c34df";
  }

  static const char* value(const ::robot_vision_lectures::XYZarray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3fb3f9dacc279b96ULL;
  static const uint64_t static_value2 = 0x4c4c8341122c34dfULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_vision_lectures::XYZarray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_vision_lectures/XYZarray";
  }

  static const char* value(const ::robot_vision_lectures::XYZarray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_vision_lectures::XYZarray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point[] points\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::robot_vision_lectures::XYZarray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_vision_lectures::XYZarray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct XYZarray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_vision_lectures::XYZarray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_vision_lectures::XYZarray_<ContainerAllocator>& v)
  {
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_VISION_LECTURES_MESSAGE_XYZARRAY_H
